apiVersion: v1
kind: Service
metadata:
  name: link-shortener-web-app-service
  namespace: frontend-backend
spec:
  selector:
    app: link-shortener-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
